import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  section: {
    flex: 1,
    justifyContent: 'space-between',
    position: 'relative',
    paddingTop: 40,
    paddingBottom: 40,
  },
  inactiveSection: { 
    opacity: 0.6,
  },
  sectionHeader: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 10,
  },
  sectionTime: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  scoreBox: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginBottom: 24,
  },
  scoreButton: {
    backgroundColor: '#e0e0e0',
    borderRadius: 8,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreButtonText: {
    color: '#333',
    fontSize: 24,
    fontWeight: 'bold',
  },
  scoreText: {
    fontSize: 48,
    fontWeight: '800',
    color: '#333',
    flex: 1,
    textAlign: 'center',
  },
  scoreMaxSeparator: {
    fontSize: 32,
    color: '#a0a0a0',
    fontWeight: '300',
    marginRight: 8,
  },
  scoreMaxText: {
    fontSize: 24,
    color: '#333',
    fontWeight: 'bold',
  },
  scoreMaxLabel: {
    fontSize: 12,
    color: '#333',
    fontWeight: 'bold',
    writingDirection: 'rtl',
    textTransform: 'uppercase',
    marginLeft: 4,
  },
  sealRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 24,
  },
  sealButton: {
    position: 'relative', 
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  sealImage: {
    position: 'absolute', 
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  sealText: {
    color: 'white', 
    fontSize: 24,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.5)', 
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 8,
  },
  statBadge: {
    backgroundColor: 'transparent',
    borderRadius: 4,
    paddingVertical: 8,
    minWidth: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statBadgeContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  statBadgeTextIcon: {
    fontSize: 24,
    color: '#ffffff',
  },
  statBadgeImage: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  statBadgeTextValue: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  passButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  passButtonText: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#FFFFFF',
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  disabledButton: { 
    opacity: 0.5,
  },
});